### ISSUE TITLE
Content.opf

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#1]
I assume that some of the stories are direct transcriptions since they don't have Gutenberg listings or are in other collections there?

I think the identifiers for github and standardebooks should be reviewed with @acabal to deal with the truncation of multiple translators.

**Comment by acabal** [comment]
Github has a char limit on repo names so we can truncate it wherever that limit is. For SE, there is no limit and we should include everyone. IIRC Robin did some work along those lines quite some time ago for the toolset, as this is not the first production with a really long repo name.

**Comment by robinwhittleton** [comment]
Yep, scans without Gutenberg transcriptions were produced from OCR by me.

Regarding identifier limits, Github caps out at 100 but we want the full identifier. I hit this before with the Ivan Bunin collection I did, and taught the linter to truncate the SE identifier to get to the repo name.
