### ISSUE TITLE
His Excellency the Governor

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#2]
Should review the use of inverted commas around "the Pike" as a nickname. I wasn't sure that they were necessary but can see an argument for inclusion.

**Comment by robinwhittleton** [comment]
They’re in the scans but I agree they hinder readability in the long term. Fixed in https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/commit/c896ed0db3811cb256120ce4cddf09d1ff69adbb.
