### ISSUE TITLE
Men May Rise on Stepping-Stones of Their Dead Selves to Higher Things

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#3]
Is there a reason why the title for Men May Rise on Stepping-Stones of Their Dead Selves to Higher Things is in inverted commas?

**Comment by robinwhittleton** [comment]
It was like that in the heading title in the source. I assuming it was a quotation from somewhere but tbf I didn’t check into it. As it’s a one-off I’ll stick with the source here.
