### ISSUE TITLE
A Dilema

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#4]
Are the first two paragraphs really an introduction or a bridgehead and should they be marked up as such?

Search for `<em>“` and replace with `“<em>` (and at the end of the sentence)
It does Look odd to have the speech marks and emphasis for the whole sentence.

Should the footer to chapter 4 really be some sort of blockquote and styled as such. A footer to a chapter seems more like a misplaced footnote whereas this is part of the plot.

**Comment by robinwhittleton** [comment]
- It’s not a bridgehead in the scans, and I can’t mark it up as a section without a heading. I think it’s fine as it is.

- Yep, fixed.

- Reasonable request. I’ve removed the footer, added an `hr` to break it away from the text above, and fixed the styling for the pseudoheader.

See https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/commit/899008dc322d308ed745ec24f5fa396e0b038d85.
