### ISSUE TITLE
The Confessions of a Little Man

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#5]
Producing lint errors about the placement of <br/> tags which should be at the end of the previous lines.

`se:letter.dateline` for the diary date should really be `se:diary.dateline`

This story contains the original publication date as the final paragraphs which should be removed.

**Comment by robinwhittleton** [comment]
- Fixed
- Oops, fixed
- 🤦‍♂️ removed

https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/commit/2159c7a30ede0220ee1e61c717db92676480a10b
