### ISSUE TITLE
Single lines broken

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#7]
Where a whole paragraph is in emphasis (occurs in a few stories) the single-line for a `<p>` has been broken and the `<em>` is indented below. (x22 in A Dilemma and The Story of the Snake)

**Comment by robinwhittleton** [comment]
Yep, this is standard SE markup style, `se clean` will do this automatically if you have a nested element with no text nodes to the left or right.

**Comment by michael-77** [comment]
I was aware that `se clean` was doing this - however it does give the appearance of `<em>` being a block level component rather than a inline component of html but there you go!
