### ISSUE TITLE
Half-title

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#8]
Is a half-title usual when there is no special front-matter?

I'm no expert on short stories!

**Comment by robinwhittleton** [comment]
No, you’re quite right, I just copied Ivan Bunin without thinking. Fixed in https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/commit/46a9f3fa2e650293a2c820cd95aca46cafe4fce8.
