### ISSUE TITLE
Suggestions from modernize-spelling

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#9]
`modernize-spelling` produces some changes for review - I'd be happy to see papa and businesslike used as suggested.

**Comment by robinwhittleton** [comment]
I’ve pushed up businesslike in https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/commit/800b4f02ed7020080a086dd9238d9583cc690627. The rest I’ve left as is:

- `red-lined` to `redlined`: redlined is I guess more about cars.
- `pa-pa` to `papa` in Vasilly: the child is meant to be pretty much unable to speak coherently
- `pit-a-pat` to `pita-pat`: tasty, but not right here :)
- `ga-ga-ga` to `gagaga`: not sure why this is better
- `pa-pa`/`ma-ma` to `papa`/`mama` in Seven: talking about a mechanical puppet
